# Generated by Django 5.0.1 on 2024-02-22 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(default="---\ntitle: My Music\n---\n")),
                ("html", models.TextField(null=True)),
                ("title", models.TextField(default="My Music")),
                ("lang", models.TextField(default="en")),
                ("meta_description", models.TextField(null=True)),
                ("meta_image", models.URLField(null=True)),
                ("navbar", models.TextField(null=True)),
                ("custom_styles", models.TextField(null=True)),
                ("custom_music_player_styles", models.TextField(null=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_discoverable", models.BooleanField(default=False)),
                ("sites", models.ManyToManyField(to="sites.site")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
