# Generated by Django 5.0.2 on 2024-02-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authusers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
