name: run tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: True
      SECRET_KEY: changeme!
      ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: sqlite:////tmp/db.sqlite3
      CORS_ORIGIN_WHITELIST: "http://localhost,http://127.0.0.1"
      CSRF_TRUSTED_ORIGINS: "http://localhost"
      S3_BUCKET_NAME: "xxx"
      S3_REGION: "us-weast"
      S3_ENDPOINT_URL: "https://s3.xxx.com"
      S3_ACCESS_KEY: "xxx"
      S3_SECRET_KEY: "xxx"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: run tests
        run: poetry run python manage.py test
